server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          skipSslValidation: true # 跳过ssl认证
          uri: git@github.com:cydxx/spring-cloud-config.git
          search-paths:
            - spring-cloud-config
      label: master
  rabbitmq:
    username: guest
    host: localhost
    password: guest
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
